
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[285] =
    {   0,
        0,    0,    0,    0,   36,   35,   33,   34,   27,   26,
       35,   17,   18,   25,   30,   35,   29,   24,   28,   24,
       32,   32,   32,   21,   22,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   19,   35,   20,   35,   35,   24,   23,    0,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   31,   32,   32,   32,   32,
       32,   32,   32,    5,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,    0,    0,    0,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   31,   32,   32,   32,
        2,   32,   32,    4,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,    0,    0,    0,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,    6,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   13,
       32,   32,    0,    1,    0,   32,   32,   32,   32,   32,
       32,   10,   32,   32,   32,   32,   31,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   31,   32,   32,    7,    0,   32,   14,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   11,   16,   12,   32,   32,   32,   32,   15,   32,
        0,   32,    3,   32,   32,   32,   32,   32,   32,   32,
       32,   32,    0,    0,   32,   32,   32,   32,   32,   32,
        0,    0,   32,   32,   32,    0,    0,   32,    0,    0,
       32,    0,    0,    0,    0,    0,    0,    0,    0,    9,
        0,    0,    8,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    6,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   22,   22,
       22,   22,   23,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   24,   22,   22,   22,   22,   22,   22,   22,
       25,   22,   26,   22,   27,   22,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   22,   37,   38,   39,   40,
       41,   42,   22,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[288] =
    {   0,
        0,    0,   22,   23,  257, 1205, 1205, 1205,  235, 1205,
      245, 1205, 1205, 1205, 1205,  214, 1205,  223,  222,  218,
       52,   53,   54,   55,   56,   57,   70,   88,   71,   79,
       86,   97,  124,  125,  127,  133,  141,  150,  164,  163,
       83, 1205,  182, 1205,  201,  185, 1205, 1205,  187,  189,
      165,  166,  188,  191,  195,  196,  197,  203,  200,  204,
      219,  220,  239,  244,  245,  248,  252,  253,  268,  270,
      271,  275,  276,  284,  298,  299,  302,  300,  303,  322,
      329,  330,  331,  344,  347,  356,  360,  361,  375,  376,
      378,  383,  173,  143,  148,  160,  380,  400,  403,  407,

      415,  416,  422,  429,  438,  445,  447,  451,  452,  454,
      460,  467,  474,  487,  494,  499,  501,  503,  108,  506,
      518,  519,  525,  531,  532,  537,  549,  550,  551,  556,
      564,  565,  568,  569,  581,  596,  598,  601,  599,  604,
      600,  142,  152,  144,  616,  618,  630,  636,  638,  642,
      643,  650,  655,  667,  669,  670,  683,  684,  686,  687,
      692,  700,  701,  714,  716,  718,  723,  730,  743,  746,
      747,  749,  750,  762,  766,  774,  778,  779,  781,  793,
      794,  797,  143, 1205,  129,  801,  809,  813,  817,  829,
      831,  836,  843,  844,  845,  848,  849,  851,  867,  874,

      875,  879,  882,  880,  883,  909,  911,  913,  914,  915,
      917,  918,  931,  946,  947,  130,  948,  949,  962,  963,
      975,  977,  979,  978,  980,  981,  982, 1004, 1008, 1010,
     1011, 1012, 1027, 1028, 1030, 1035, 1042, 1043, 1205, 1058,
      121, 1044, 1060, 1061, 1073, 1074, 1077, 1078, 1091, 1092,
     1097, 1109,  111,  102, 1111, 1117, 1123, 1136, 1137, 1142,
      117,   95, 1145, 1143, 1151,   94,  119, 1165,   65,   66,
     1168,   75,   59,   72,   56,   51,   50,   33,   30, 1205,
       28,   25, 1205, 1205, 1202,   62,   55
    } ;

static yyconst flex_int16_t yy_def[288] =
    {   0,
      284,    1,  285,  285,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
       28,   28,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  284,  284,  284,  284,  284,  284,  284,  284,  287,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  284,  284,  284,  287,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,   28,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  284,  284,  284,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  284,  284,  284,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  284,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  284,  286,
      284,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  284,  284,  286,  286,  286,  286,  286,  286,
      284,  284,  286,  286,  286,  284,  284,  286,  284,  284,
      286,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,    0,  284,  284,  284
    } ;

static yyconst flex_int16_t yy_nxt[1260] =
    {   0,
        6,    7,    8,    7,    9,    6,   10,   11,   12,   13,
       10,   14,   15,   14,   16,   10,    6,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   21,   26,   27,   28,
       29,   30,   31,   32,   21,   33,   21,   34,   21,   35,
       21,   36,   37,   38,   39,   21,   40,   41,   21,   21,
       21,   42,   43,   44,   45,   45,   50,   50,   50,   50,
       50,   50,   50,   51,  283,  282,   46,   46,   50,   50,
       50,   50,   50,   50,  281,   50,   50,  280,   52,   52,
       52,   52,   52,   52,   50,   56,   50,   50,   50,  279,
      278,  277,   53,   50,  276,   50,   52,   52,   54,   50,

       57,  275,   65,   55,   50,   52,  274,  273,  272,   52,
       58,   66,   59,   51,   52,   61,   67,   92,   68,   60,
       51,   70,   62,   71,   51,   63,   72,   69,   64,   50,
       50,   51,   50,  270,   51,   51,  269,   73,   50,  267,
       50,   50,   51,   50,  266,  162,   50,  262,  163,   50,
       52,   52,  261,   52,   78,   50,   74,   50,   79,   52,
       80,  254,   75,   76,  239,   77,   50,   52,   50,   50,
       50,   50,   83,  216,  184,   81,   52,  185,   82,   50,
       50,   50,   50,  184,   84,  183,   96,  144,  143,   52,
       52,   52,   52,   50,   85,   86,   50,   87,   89,   88,

       50,   50,   50,   91,   50,   50,   90,   50,   50,   50,
      142,   50,   50,   50,   52,   96,   50,   52,   95,   50,
       50,   52,   52,   52,   50,   50,   52,   94,   93,   52,
       52,  103,   97,   98,   48,   50,   50,   47,   99,  100,
      101,   47,   47,  102,   50,   52,   52,  107,  104,   50,
       50,   49,   48,   50,   47,   50,  284,   50,   50,  284,
       50,   50,  105,  106,   50,   52,  108,  284,   50,   50,
       52,   52,  284,   50,   52,   50,   50,  110,   52,   52,
       50,   50,  284,  109,   50,  284,   50,   50,  284,   50,
      284,   50,   50,  111,   52,  112,   52,   52,  113,  284,

       50,   52,   52,   50,   50,   50,  284,   50,   50,  115,
       52,  116,  114,  284,   50,   50,   50,  117,   50,   50,
      118,  284,  284,  284,   52,   52,   52,   50,   52,   52,
      284,  284,  284,  284,   50,   50,   50,  284,   50,  119,
      284,  122,  120,  121,  123,   50,   50,   50,   52,   50,
      124,  125,   50,  284,  284,   52,   52,   52,  128,  284,
       50,   50,  284,   50,  126,   50,   50,  284,  284,  127,
       52,  284,   50,   52,  131,  129,   50,   50,  284,  284,
       50,   50,   52,   50,  130,   50,   52,   52,   50,  132,
      284,   50,   50,  284,   50,  134,   50,  133,  284,   50,

      135,   52,   52,  138,   52,   50,   52,  284,   50,   52,
      136,  145,   50,  139,  284,  140,   50,  137,  141,   50,
       50,   50,  284,   50,  284,  117,   52,   50,  284,   52,
      284,   50,   50,   52,   50,  146,  284,  284,   50,  284,
      284,   52,   52,   50,  284,   50,  149,  147,   52,  151,
       50,  148,   50,  150,   50,   52,   50,   50,  284,   50,
      117,   50,  284,   50,   52,   50,  284,   50,   50,  117,
       50,   52,   50,   52,  152,  284,   50,   52,   52,   50,
       52,  156,  284,   50,  284,  284,   52,  284,  157,  117,
       50,  284,   50,   52,  153,  154,  155,  284,  158,   50,

       52,  284,  284,   50,   50,  284,   50,  284,   50,  284,
       50,   50,  117,   52,  284,   50,  284,   50,  159,   50,
       52,  160,   50,   50,   50,   52,  161,   52,  284,   52,
       50,  284,   52,  284,   50,   50,   50,   50,  284,  284,
      284,   50,   50,  117,   52,   52,  284,   50,   50,  165,
      164,   52,  117,   50,   50,   50,   50,   52,   52,  284,
      166,   50,  284,   52,  284,   50,   50,   50,  167,   50,
       50,  284,   50,   50,   50,   52,   52,   52,  284,  284,
       50,   50,   52,  168,   50,   50,   50,  170,  284,  284,
       52,   52,  284,  169,   52,   52,  171,   50,  172,  175,

      174,   50,  284,   50,   50,   50,   50,   52,  173,   50,
      177,  284,   50,  176,   50,   50,   50,   50,  284,  284,
       50,   50,   52,   50,   52,   52,   52,   52,  284,  180,
       52,  181,   50,  284,   50,   50,  284,  182,  178,  117,
      179,   50,   52,   50,   52,  284,   50,   50,   50,  186,
      284,  284,   50,  284,   50,   50,   52,  187,   50,   50,
       50,  188,   52,  284,   52,  284,   50,  284,   52,   52,
      284,   50,   50,  191,   50,   50,   52,  284,  189,  117,
      190,   52,  284,   50,  117,   50,   50,  284,   50,   50,
      284,   50,   50,   52,  284,   52,   52,   50,  192,   50,

       50,  284,   50,   50,  193,   50,   50,  284,   50,   52,
       52,  117,   52,   52,  284,  194,   50,   50,   52,   50,
      195,   50,  284,   50,  197,  196,   52,   52,   50,  284,
       50,  198,   50,  284,   50,   50,  117,  284,  284,   50,
       52,  200,   52,  199,   52,  284,   50,  284,   50,   52,
      203,   50,   50,  284,   50,   50,   52,  204,  201,   50,
      284,  284,   50,   50,  202,   50,   50,   50,  284,   52,
      284,   50,   52,   52,  205,   52,   52,  284,   50,   50,
      284,  206,   50,   50,   50,  208,   50,  284,   52,  207,
       50,  209,   52,  117,   50,   50,  284,   50,   50,   50,

       52,  284,   50,  210,   52,   52,   50,   52,  117,   50,
       50,  284,  211,   50,   50,  284,  284,   50,   50,   52,
       52,  284,   50,   52,  213,   50,  212,   52,  215,   50,
      284,  284,  217,   50,   50,   52,   50,  284,  214,   52,
      284,   50,  218,   52,  220,   50,  284,   50,   50,   50,
       50,  219,   50,   50,   50,   52,   50,   52,  221,   50,
       50,   50,   52,  284,   50,   50,  284,   50,  284,   52,
       52,   52,   50,  117,   52,   52,  117,   52,  224,   50,
       50,  223,  222,   50,   50,   50,  225,   50,   50,  226,
       50,   50,  284,   52,  284,   50,   50,  284,   50,   50,

       52,   52,  284,  284,  284,   52,   52,  228,   52,   52,
      117,  117,  231,  227,   50,  229,   50,  284,   50,   50,
       50,  284,   50,   50,  230,   50,  284,   50,  284,   50,
       50,   50,  284,   50,   50,   52,   50,   52,  232,   52,
       52,   52,  234,   52,   52,  284,  284,   50,  284,  117,
      233,   50,   50,   50,   50,  284,  284,   52,  235,  236,
      284,  117,   50,   50,   50,   50,  237,   50,   50,  284,
      284,  284,   52,   52,   52,   52,  241,  284,   50,   50,
       50,  238,   50,   50,   50,   50,   50,   50,   52,   52,
      240,   50,  242,   50,   50,   50,   50,   50,   50,  284,

      284,   52,  284,   52,   52,   52,   52,   52,   52,   50,
      284,  246,  245,   50,  243,   50,   50,   50,  284,  284,
       50,  117,  244,  117,   50,  284,   50,   50,   50,  117,
       52,  247,   50,   50,   52,   50,   52,   52,   52,  117,
       50,  117,  284,   50,   50,  284,   50,   50,   50,   50,
      284,   50,  284,   52,   52,  248,   52,  284,   50,   50,
       50,   52,  249,   50,  284,   50,   50,  284,   52,   52,
       52,  284,  253,  251,   50,  250,   50,   50,   50,   50,
      252,  284,   50,   50,   52,  284,   52,   52,  117,   50,
       50,  284,  117,   50,   50,  284,   50,   50,  284,   52,

       52,  284,   50,   52,   52,  256,  257,   50,   50,  258,
      284,  284,  255,   50,   50,  284,   50,   52,   52,  284,
      284,  284,   50,   52,  284,   50,  284,   50,   50,  284,
      284,  259,  117,   50,  284,   52,  260,   52,  284,   50,
      117,   50,   50,   52,  284,  284,  284,   50,   50,   52,
       50,  284,   50,   50,  117,  263,   50,  264,   50,   50,
      284,   50,   52,   52,  284,  284,  117,   50,   52,   52,
       50,   52,  265,   50,  284,  117,  284,   52,  284,  284,
      284,   50,  284,  284,   50,  284,  117,  284,  117,  284,
      284,   52,  284,  284,   52,  284,  271,  284,  117,  284,

      284,  268,    6,    6,    5,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yyconst flex_int16_t yy_chk[1260] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,  287,   21,   22,   23,
       24,   25,   26,  286,  282,  281,    3,    4,   21,   22,
       23,   24,   25,   26,  279,   27,   29,  278,   21,   22,
       23,   24,   25,   26,   30,   26,   27,   29,   41,  277,
      276,  275,   22,   28,  274,   30,   27,   29,   23,   41,

       26,  273,   29,   23,   28,   30,  272,  270,  269,   41,
       27,   29,   27,   31,   28,   28,   30,   41,   30,   27,
       31,   31,   28,   31,   32,   28,   31,   30,   28,   33,
       34,   32,   35,  267,   32,  119,  266,   32,   36,  262,
       33,   34,  119,   35,  261,  119,   37,  254,  119,   36,
       33,   34,  253,   35,   35,   38,   33,   37,   35,   36,
       36,  241,   33,   33,  216,   34,   38,   37,   40,   39,
       51,   52,   37,  185,  183,   36,   38,  144,   36,   40,
       39,   51,   52,  143,   38,  142,   96,   95,   94,   40,
       39,   51,   52,   53,   38,   38,   54,   38,   39,   38,

       55,   56,   57,   40,   53,   59,   39,   54,   58,   60,
       93,   55,   56,   57,   53,   50,   59,   54,   49,   58,
       60,   55,   56,   57,   61,   62,   59,   46,   45,   58,
       60,   59,   53,   54,   43,   61,   62,   20,   55,   56,
       57,   19,   18,   58,   63,   61,   62,   62,   60,   64,
       65,   16,   11,   66,    9,   63,    5,   67,   68,    0,
       64,   65,   61,   61,   66,   63,   63,    0,   67,   68,
       64,   65,    0,   69,   66,   70,   71,   65,   67,   68,
       72,   73,    0,   64,   69,    0,   70,   71,    0,   74,
        0,   72,   73,   66,   69,   67,   70,   71,   68,    0,

       74,   72,   73,   75,   76,   78,    0,   77,   79,   70,
       74,   71,   69,    0,   75,   76,   78,   72,   77,   79,
       73,    0,    0,    0,   75,   76,   78,   80,   77,   79,
        0,    0,    0,    0,   81,   82,   83,    0,   80,   75,
        0,   77,   76,   76,   78,   81,   82,   83,   80,   84,
       79,   80,   85,    0,    0,   81,   82,   83,   82,    0,
       84,   86,    0,   85,   81,   87,   88,    0,    0,   81,
       84,    0,   86,   85,   85,   83,   87,   88,    0,    0,
       89,   90,   86,   91,   84,   97,   87,   88,   92,   85,
        0,   89,   90,    0,   91,   87,   97,   86,    0,   92,

       88,   89,   90,   90,   91,   98,   97,    0,   99,   92,
       89,   97,  100,   91,    0,   91,   98,   89,   92,   99,
      101,  102,    0,  100,    0,   90,   98,  103,    0,   99,
        0,  101,  102,  100,  104,   98,    0,    0,  103,    0,
        0,  101,  102,  105,    0,  104,  101,   99,  103,  103,
      106,  100,  107,  102,  105,  104,  108,  109,    0,  110,
      104,  106,    0,  107,  105,  111,    0,  108,  109,  105,
      110,  106,  112,  107,  106,    0,  111,  108,  109,  113,
      110,  110,    0,  112,    0,    0,  111,    0,  111,  107,
      113,    0,  114,  112,  108,  109,  109,    0,  112,  115,

      113,    0,    0,  114,  116,    0,  117,    0,  118,    0,
      115,  120,  113,  114,    0,  116,    0,  117,  114,  118,
      115,  115,  120,  121,  122,  116,  116,  117,    0,  118,
      123,    0,  120,    0,  121,  122,  124,  125,    0,    0,
        0,  123,  126,  118,  121,  122,    0,  124,  125,  121,
      120,  123,  122,  126,  127,  128,  129,  124,  125,    0,
      123,  130,    0,  126,    0,  127,  128,  129,  125,  131,
      132,    0,  130,  133,  134,  127,  128,  129,    0,    0,
      131,  132,  130,  126,  133,  134,  135,  128,    0,    0,
      131,  132,    0,  127,  133,  134,  129,  135,  130,  133,

      132,  136,    0,  137,  139,  141,  138,  135,  131,  140,
      135,    0,  136,  134,  137,  139,  141,  138,    0,    0,
      140,  145,  136,  146,  137,  139,  141,  138,    0,  139,
      140,  140,  145,    0,  146,  147,    0,  141,  137,  136,
      138,  148,  145,  149,  146,    0,  147,  150,  151,  145,
        0,    0,  148,    0,  149,  152,  147,  146,  150,  151,
      153,  147,  148,    0,  149,    0,  152,    0,  150,  151,
        0,  153,  154,  150,  155,  156,  152,    0,  148,  151,
      149,  153,    0,  154,  152,  155,  156,    0,  157,  158,
        0,  159,  160,  154,    0,  155,  156,  161,  153,  157,

      158,    0,  159,  160,  155,  162,  163,    0,  161,  157,
      158,  154,  159,  160,    0,  156,  162,  163,  161,  164,
      157,  165,    0,  166,  160,  159,  162,  163,  167,    0,
      164,  162,  165,    0,  166,  168,  161,    0,    0,  167,
      164,  164,  165,  163,  166,    0,  168,    0,  169,  167,
      167,  170,  171,    0,  172,  173,  168,  168,  165,  169,
        0,    0,  170,  171,  166,  172,  173,  174,    0,  169,
        0,  175,  170,  171,  169,  172,  173,    0,  174,  176,
        0,  170,  175,  177,  178,  173,  179,    0,  174,  171,
      176,  174,  175,  172,  177,  178,    0,  179,  180,  181,

      176,    0,  182,  176,  177,  178,  186,  179,  175,  180,
      181,    0,  177,  182,  187,    0,    0,  186,  188,  180,
      181,    0,  189,  182,  179,  187,  178,  186,  182,  188,
        0,    0,  186,  189,  190,  187,  191,    0,  181,  188,
        0,  192,  187,  189,  189,  190,    0,  191,  193,  194,
      195,  188,  192,  196,  197,  190,  198,  191,  191,  193,
      194,  195,  192,    0,  196,  197,    0,  198,    0,  193,
      194,  195,  199,  190,  196,  197,  195,  198,  196,  200,
      201,  194,  193,  199,  202,  204,  197,  203,  205,  198,
      200,  201,    0,  199,    0,  202,  204,    0,  203,  205,

      200,  201,    0,    0,    0,  202,  204,  201,  203,  205,
      202,  199,  205,  200,  206,  203,  207,    0,  208,  209,
      210,    0,  211,  212,  204,  206,    0,  207,    0,  208,
      209,  210,    0,  211,  212,  206,  213,  207,  206,  208,
      209,  210,  208,  211,  212,    0,    0,  213,    0,  210,
      207,  214,  215,  217,  218,    0,    0,  213,  209,  211,
        0,  212,  214,  215,  217,  218,  213,  219,  220,    0,
        0,    0,  214,  215,  217,  218,  219,    0,  219,  220,
      221,  214,  222,  224,  223,  225,  226,  227,  219,  220,
      217,  221,  220,  222,  224,  223,  225,  226,  227,    0,

        0,  221,    0,  222,  224,  223,  225,  226,  227,  228,
        0,  227,  226,  229,  221,  230,  231,  232,    0,    0,
      228,  224,  222,  223,  229,    0,  230,  231,  232,  225,
      228,  228,  233,  234,  229,  235,  230,  231,  232,  229,
      236,  230,    0,  233,  234,    0,  235,  237,  238,  242,
        0,  236,    0,  233,  234,  231,  235,    0,  237,  238,
      242,  236,  235,  240,    0,  243,  244,    0,  237,  238,
      242,    0,  240,  237,  240,  236,  243,  244,  245,  246,
      238,    0,  247,  248,  240,    0,  243,  244,  242,  245,
      246,    0,  244,  247,  248,    0,  249,  250,    0,  245,

      246,    0,  251,  247,  248,  246,  247,  249,  250,  248,
        0,    0,  245,  251,  252,    0,  255,  249,  250,    0,
        0,    0,  256,  251,    0,  252,    0,  255,  257,    0,
        0,  250,  249,  256,    0,  252,  251,  255,    0,  257,
      252,  258,  259,  256,    0,    0,    0,  260,  264,  257,
      263,    0,  258,  259,  257,  255,  265,  256,  260,  264,
        0,  263,  258,  259,    0,    0,  258,  265,  260,  264,
      268,  263,  259,  271,    0,  264,    0,  265,    0,    0,
        0,  268,    0,    0,  271,    0,  260,    0,  263,    0,
        0,  268,    0,    0,  271,    0,  268,    0,  271,    0,

        0,  265,  285,  285,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "projecto.l"
#line 2 "projecto.l"
int line=1;
int column=1;

#line 831 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 7 "projecto.l"

#line 1021 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1205 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 10 "projecto.l"
{printf("BOOLLIT\n");column+=yyleng;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 11 "projecto.l"
{printf("INT\n");column+=yyleng;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 12 "projecto.l"
{printf("BOOL\n");column+=yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 13 "projecto.l"
{printf("NEW\n");column+=yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 14 "projecto.l"
{printf("IF\n");column+=yyleng;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 15 "projecto.l"
{printf("ELSE\n");column+=yyleng;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 16 "projecto.l"
{printf("WHILE\n");column+=yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 17 "projecto.l"
{printf("PRINT\n");column+=yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 18 "projecto.l"
{printf("PARSEINT\n");column+=yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 19 "projecto.l"
{printf("CLASS\n");column+=yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 20 "projecto.l"
{printf("PUBLIC\n");column+=yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 21 "projecto.l"
{printf("STATIC\n");column+=yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 22 "projecto.l"
{printf("VOID\n");column+=yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 23 "projecto.l"
{printf("STRING\n");column+=yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 24 "projecto.l"
{printf("DOTLENGTH\n");column+=yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 25 "projecto.l"
{printf("RETURN\n");column+=yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 26 "projecto.l"
{printf("OCURV\n");column+=yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 27 "projecto.l"
{printf("CCURV\n");column+=yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 28 "projecto.l"
{printf("OBRACE\n");column+=yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 29 "projecto.l"
{printf("CBRACE\n");column+=yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 30 "projecto.l"
{printf("OSQUARE\n");column+=yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 31 "projecto.l"
{printf("CSQUARE\n");column+=yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 32 "projecto.l"
{printf("OP1\n");column+=yyleng;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 33 "projecto.l"
{printf("OP2\n");column+=yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 34 "projecto.l"
{printf("OP3\n");column+=yyleng;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 35 "projecto.l"
{printf("OP4\n");column+=yyleng;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 36 "projecto.l"
{printf("NOT\n");column+=yyleng;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 37 "projecto.l"
{printf("ASSIGN\n");column+=yyleng;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 38 "projecto.l"
{printf("SEMIC\n");column+=yyleng;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 39 "projecto.l"
{printf("COMMA\n");column+=yyleng;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 41 "projecto.l"
{printf("RESERVED\n");column+=yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 42 "projecto.l"
{printf("ID(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 43 "projecto.l"
{column+=yyleng;}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 44 "projecto.l"
{line++;column = 0;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "projecto.l"
ECHO;
	YY_BREAK
#line 1280 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 284);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 47 "projecto.l"



int main()
{
	yylex();
}

int yywrap()
{
return 1;
}

